variant: openshift
version: 4.13.0
metadata:
  name: 99-master-installation-configuration
  labels:
    machineconfiguration.openshift.io/role: master
storage:
  files:
    - path: /usr/local/bin/installation-configuration.sh
      mode: 0755
      overwrite: true
      contents:
        local: installation-configuration.sh
    - path: /usr/local/bin/pre-network-manager-config.sh
      mode: 493
      overwrite: true
      contents:
        local: pre-network-manager-config.sh
systemd:
  units:
    - name: image-base-configuration.service
      enabled: true
      contents: |
        [Unit]
        Description=Image base SNO configuration script
        [Service]
        WorkingDirectory=/opt/openshift
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/local/bin/installation-configuration.sh
        [Install]
        WantedBy=multi-user.target